version: '3'
services:
  app:
    container_name: app
    image: mocacong/mocacong
    expose:
      - "8080"
    ports:  # host - container 포트 매핑
      - "8080:8080"
    volumes: # host 로그 디렉토리 - container 로그 디렉토리 볼륨 마운트
      - ./logs:/logs
